import type { Metadata } from "next";
import "./globals.css";
import { GlobalLayout } from "@/main/components/layouts/global-layout";
import { defaultFont } from "@/main/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${defaultFont.className} antialiased`}>
        <GlobalLayout>{children}</GlobalLayout>
      </body>
    </html>
  );
}
